version: '3'

services:
  db:
    image: postgres:10.3-alpine
    volumes:
      - db:/var/lib/postgresql/data
#redis
#redis  redis:
#redis    image: redis:4.0-alpine
#redis    command: redis-server
#redis    volumes:
#redis      - redis:/data
#mongo
#mongo  mongo:
#mongo    image: mongo:3.6.4
#mongo    volumes:
#mongo      - mongo:/db/data

  web: &web
    depends_on:
      - db
#redis      - redis
#mongo      - mongo
    image: civica-digital/{{app_name}}:development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src
      - gems:/usr/local/bundle
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
#redis      - REDIS_URL=redis://redis:6379
#mongo      - MONGO_URL=mongodb://mongo:27017

#sidekiq  sidekiq:
#sidekiq    <<: *web
#sidekiq    command: sidekiq -q default -q mailers
#sidekiq
#scheduler  scheduler:
#scheduler    <<: *web
#scheduler    command: ofelia daemon --config /usr/src/config/ofelia.ini
#scheduler
volumes:
  db:
#redis  redis:
#mongo  mongo:
  gems:
