version: '3'

services:
  postgres:
    image: postgres:10.3-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:4.0-alpine
    command: redis-server
    volumes:
      - redis:/data
#
#  mongo:
#    image: mongo:3.6.4
#    volumes:
#      - mongo:/db/data

  web: &web
    depends_on:
      - postgres
      - redis
#      - mongo
    image: civica-digital/{{app_name}}:development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src
      - gems:/usr/local/bundle
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_HOST=postgres
      - REDIS_URL=redis://redis:6379
#      - MONGO_URL=mongodb://mongo:27017

  sidekiq:
    <<: *web
    command: sidekiq -q default -q mailers

volumes:
  postgres:
  redis:
#  mongo:
  gems:
