default: &default
  adapter: postgresql
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DATABASE_USERNAME') { `whoami` } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { '' } %>

development:
  <<: *default
  database: {{app_name}}_development

test:
  <<: *default
  database: {{app_name}}_test

production:
  adapter: postgresql
  url: <%= ENV.fetch('DATABASE_URL') { '' } %>
